export const BINGO_OPTIONS = [
  "Mike's Pastry Box",
  "Smell of Weed",
  "Doing Yoga",
  "Scooter Kid",
  "Adult Chasing Kid",
  "Slangin' Frisbee (175g)",
  "Feeding Wildlife",
  "Dog Actively Pooping",
  "Colonial Actor",
  "Influencer in the Wild",
  "Phone Eats First",
  "Squad of 3 or More Bluebikes",
  "Abandoned Bluebike",
  "Engagement Pictures",
  "Wedding Pictures",
  "A Rally",
  "A Political Statement",
  "A Proposal",
  "Yankee Paraphernalia",
  "Bad Sunburn",
  "Blatant Tourism",
  "Indecent Exposure",
  "A Horse",
  "In trouble with Law Enforcement",
  "Excessively Loud Music",
  "Rollerblader in Full Pads",
  "Police Sirens",
  "5 or More Retail Bags",
  "Dropped Ice Cream",
  "Sleeping",
  "RC Car Dad",
  "Regina Pizza Box",
  "Dozen of abandoned masks",
  "Kid chasing pigeons",
  "Wasted",
  "A Nipple",
  "A Flying Kite",
  "An Act of Kindness",
  "Organized Sports",
  "Hammock",
];
